// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // ✅ FIXED: Added Android support
      case TargetPlatform.iOS:
        return ios; // ✅ FIXED: Added iOS support
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxKS-VQCfDpjo4KZ2sMoFW8NaCEhKh4Jo',
    appId: '1:95759348559:web:1b9e2892f3da467173cb3a',
    messagingSenderId: '95759348559',
    projectId: 'menuplanner-ee8a0',
    authDomain: 'menuplanner-ee8a0.firebaseapp.com',
    storageBucket: 'menuplanner-ee8a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyDj6RWm5sbly5VOVnl3WEXACRY_eNsnl4E', 
  appId: '1:95759348559:android:66fd96b286a4b27773cb3a',
  messagingSenderId: '95759348559',
  projectId: 'menuplanner-ee8a0',
  storageBucket: 'menuplanner-ee8a0.firebasestorage.app',
);


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // ✅ Replace with your actual Firebase iOS API Key
    appId: 'YOUR_IOS_APP_ID', // ✅ Replace with your actual Firebase iOS App ID
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'menuplanner-ee8a0',
    storageBucket: 'menuplanner-ee8a0.firebasestorage.app',
    iosBundleId: 'com.example.menuPlanner', // ✅ Ensure this matches your iOS app bundle ID
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAdVz82SJpn8nhgUIrq9lvn6zi2JZYxQ4',
    appId: '1:95759348559:ios:0e9acd8ac67cf35573cb3a',
    messagingSenderId: '95759348559',
    projectId: 'menuplanner-ee8a0',
    storageBucket: 'menuplanner-ee8a0.firebasestorage.app',
    iosClientId: '95759348559-9pgjbtph4fj32k0507rjoq8dijlvfso0.apps.googleusercontent.com',
    iosBundleId: 'com.example.menuPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxKS-VQCfDpjo4KZ2sMoFW8NaCEhKh4Jo',
    appId: '1:95759348559:web:7a0fb4644d9618fb73cb3a',
    messagingSenderId: '95759348559',
    projectId: 'menuplanner-ee8a0',
    authDomain: 'menuplanner-ee8a0.firebaseapp.com',
    storageBucket: 'menuplanner-ee8a0.firebasestorage.app',
  );

}